name = "Aberacon 2025"
url = "http://furrycons.com/event/26025/aberacon-2025"
start_date = "2025-08-23"
end_date = "2025-08-24"
address = "Best Western Aberavon Beach Hotel, Port Talbot, UK"
country = "GB"
lat_lng = [51.5934371, -3.8149078]
