name = "Alamo City Furry Invasion 2025"
url = "http://furrycons.com/event/25396/alamo-city-furry-invasion-2025"
start_date = "2025-10-09"
end_date = "2025-10-12"
address = "Embassy Suites by Hilton San Marcos Hotel Conference Center, San Marcos, TX, USA"
country = "US"
lat_lng = [29.839588, -97.9695576]
