name = "Anthro New England 2026"
url = "http://furrycons.com/event/26040/anthro-new-england-2026"
start_date = "2026-01-15"
end_date = "2026-01-18"
address = "The Westin Boston Seaport District, Boston, MA, USA"
country = "US"
lat_lng = [42.3459634, -71.0433385]
