name = "AnthroTales 2026"
url = "http://furrycons.com/event/26208/anthrotales-2026"
start_date = "2026-05-14"
end_date = "2026-05-17"
address = "Van der Valk Hotel Mons Congrès & Spa, Mons, Belgium"
country = "BE"
lat_lng = [50.4563266, 3.9406037]
