name = "Anthro Northwest 2026"
url = "http://furrycons.com/event/25965/anthro-northwest-2026"
startDate = "2025-12-31"
endDate = "2026-01-04"
address = "Hyatt Regency Seattle, Seattle, WA, USA"
country = "US"
latLng = [ 47.6145295, -122.3342642,]
