name = "Anthro New England 2026"
url = "http://furrycons.com/event/26040/anthro-new-england-2026"
startDate = "2026-01-15"
endDate = "2026-01-18"
address = "The Westin Boston Seaport District, Boston, MA, USA"
country = "US"
latLng = [ 42.3459634, -71.0433385,]
