name = "Anthrocon 2026"
url = "http://furrycons.com/event/26300/anthrocon-2026"
startDate = "2026-07-02"
endDate = "2026-07-05"
address = "David L. Lawrence Convention Center, Pittsburgh, PA, USA"
country = "US"
latLng = [ 40.4456408, -79.9963595,]
source = "fancons.com"
