name = "Anthros & Alpine 2026"
url = "http://furrycons.com/event/26353/anthros-and-alpine-2026"
start_date = "2026-01-29"
end_date = "2026-02-01"
address = "Sole Gjestegård, Noresund, Norway"
country = "NO"
lat_lng = [60.1755457, 9.6308097]
