name = "Anthrocon 2026"
url = "http://furrycons.com/event/26300/anthrocon-2026"
start_date = "2026-07-02"
end_date = "2026-07-05"
address = "David L. Lawrence Convention Center, Pittsburgh, PA, USA"
country = "US"
lat_lng = [40.4456408, -79.9963595]
