name = "Anthro Northwest 2026"
url = "http://furrycons.com/event/25965/anthro-northwest-2026"
start_date = "2025-12-31"
end_date = "2026-01-04"
address = "Hyatt Regency Seattle, Seattle, WA, USA"
country = "US"
lat_lng = [47.6145295, -122.3342642]
