name = "Aurawra 2025"
url = "http://furrycons.com/event/24629/aurawra-2025"
start_date = "2025-07-25"
end_date = "2025-07-27"
address = "ParkRoyal Parramatta, Parramatta, New South Wales, Australia"
country = "AU"
lat_lng = [-33.8122336, 151.0050208]
