name = "Aurawra 2025"
url = "http://furrycons.com/event/24629/aurawra-2025"
startDate = "2025-07-25"
endDate = "2025-07-27"
address = "ParkRoyal Parramatta, Parramatta, New South Wales, Australia"
country = "AU"
latLng = [ -33.8122336, 151.0050208,]
