name = "Barkada Furfest 2025"
url = "http://furrycons.com/event/26207/barkada-furfest-2025"
startDate = "2025-09-06"
endDate = "2025-09-07"
address = "Sequoia Hotel Manila Bay, Paranaque City, Metro Manila, Philippines"
country = "PH"
latLng = [ 14.5264269, 120.991848,]
