name = "Big Sky Camp Paw 2025"
url = "http://furrycons.com/event/26017/big-sky-camp-paw-2025"
start_date = "2025-08-07"
end_date = "2025-08-11"
address = "Hellgate Campground, Helena, MT, USA"
country = "US"
lat_lng = [46.6186255, -111.645415]
