name = "Calfurry 2026"
url = "http://furrycons.com/event/26177/calfurry-2026"
start_date = "2026-09-04"
end_date = "2026-09-06"
address = "The Glenmore Inn & Convention Centre, Calgary, Alberta, Canada"
country = "CA"
lat_lng = [50.9802653, -113.9969993]
