name = "Campfire Tails 2025"
url = "http://furrycons.com/event/25694/campfire-tails-2025"
start_date = "2025-07-31"
end_date = "2025-08-04"
address = "Deschutes National Forest, Ogden Group Camp, La Pine, OR, USA"
country = "US"
lat_lng = [43.7291532, -121.422049]
