name = "Camp Mani-Toebeans 2025"
url = "http://furrycons.com/event/26064/camp-mani-toebeans-2025"
start_date = "2025-08-29"
end_date = "2025-09-01"
address = "Camp Wasaga, Onanole, Manitoba, Canada"
country = "CA"
lat_lng = [50.6643164, -100.0189377]
