name = "CanFURence 2025"
url = "http://furrycons.com/event/24718/canfurence-2025"
startDate = "2025-08-01"
endDate = "2025-08-03"
address = "Delta Hotels by Marriott Ottawa City Centre, Ottawa, Ontario, Canada"
country = "CA"
latLng = [ 45.4186734, -75.7042909,]
