name = "Carolina Furfare 2025"
url = "http://furrycons.com/event/25982/carolina-furfare-2025"
startDate = "2025-11-06"
endDate = "2025-11-09"
address = "Hickory Metro Convention Center, Hickory, NC, USA"
country = "US"
latLng = [ 35.7091466, -81.3040744,]
