name = "Carolina Furfare 2025"
url = "http://furrycons.com/event/25982/carolina-furfare-2025"
start_date = "2025-11-06"
end_date = "2025-11-09"
address = "Hickory Metro Convention Center, Hickory, NC, USA"
country = "US"
lat_lng = [35.7091466, -81.3040744]
