name = "Confuror 2025"
url = "http://furrycons.com/event/26051/confuror-2025"
start_date = "2025-10-23"
end_date = "2025-10-26"
address = "Expo Guadalajara, Guadalajara, JAL, Mexico"
country = "MX"
lat_lng = [20.6529938, -103.3917165]
