name = "Confuror 2025"
url = "http://furrycons.com/event/26051/confuror-2025"
startDate = "2025-10-23"
endDate = "2025-10-26"
address = "Expo Guadalajara, Guadalajara, JAL, Mexico"
country = "MX"
latLng = [ 20.6529938, -103.3917165,]
source = "fancons.com"
