name = "DenFur 2025"
url = "http://furrycons.com/event/25259/denfur-2025"
startDate = "2025-08-29"
endDate = "2025-08-31"
address = "Sheraton Denver Downtown Hotel, Denver, CO, USA"
country = "US"
latLng = [ 39.7419647, -104.9891354,]
source = "fancons.com"
