name = "Dutch Furcon 2025"
url = "http://furrycons.com/event/26054/dutch-furcon-2025"
startDate = "2025-08-08"
endDate = "2025-08-10"
address = "Vakantiepark de Oude Molen, Groesbeek, Netherlands"
country = "NL"
latLng = [ 51.7845123, 5.9351461,]
source = "fancons.com"
