name = "Dutch Furcon 2025"
url = "http://furrycons.com/event/26054/dutch-furcon-2025"
start_date = "2025-08-08"
end_date = "2025-08-10"
address = "Vakantiepark de Oude Molen, Groesbeek, Netherlands"
country = "NL"
lat_lng = [51.7845123, 5.9351461]
