name = "East 2025"
url = "http://furrycons.com/event/26011/east-2025"
start_date = "2025-09-17"
end_date = "2025-09-21"
address = "Ringberg Hotel Suhl, Suhl, Germany"
country = "DE"
lat_lng = [50.6169277, 10.7229427]
