name = "Eurofurence 2025"
url = "http://furrycons.com/event/25335/eurofurence-2025"
startDate = "2025-09-03"
endDate = "2025-09-06"
address = "Congress Center Hamburg, Hamburg, Germany"
country = "DE"
latLng = [ 53.561764, 9.9857445,]
