name = "Eurofurence 2025"
url = "http://furrycons.com/event/25335/eurofurence-2025"
start_date = "2025-09-03"
end_date = "2025-09-06"
address = "Congress Center Hamburg, Hamburg, Germany"
country = "DE"
lat_lng = [53.561764, 9.9857445]
