name = "Eurofurence 2025"
url = "https://www.eurofurence.org"
startDate = "2025-09-03"
endDate = "2025-09-06"
address = "Congress Center Hamburg, Hamburg, Germany"
country = "DE"
latLng = [53.561764, 9.9857445]
source = "fancons.com"
