name = "Fur the 'More 2026"
url = "http://furrycons.com/event/26133/fur-the--more-2026"
startDate = "2026-03-27"
endDate = "2026-03-29"
address = "Lord Baltimore Hotel / Kimpton Hotel Monaco Baltimore Inner Harbor, Baltimore, MD, USA"
country = "US"
latLng = [ 39.2897767, -76.6158445,]
source = "fancons.com"
