name = "FurcoNZ Hotel 2025"
url = "http://furrycons.com/event/26016/furconz-hotel-2025"
startDate = "2025-11-21"
endDate = "2025-11-23"
address = "Holiday Inn Auckland Airport, Auckland, New Zealand"
country = "NZ"
latLng = [-36.9731132, 174.7855693]
