name = "Furcamp 2026"
url = "http://furrycons.com/event/25460/furcamp-2026"
start_date = "2026-02-14"
end_date = "2026-02-17"
address = "Acampamento Terra do Saber, Franco da Rocha, SP, Brazil"
country = "BR"
lat_lng = [-23.3193571, -46.7862628]
