name = "Furdance Budapest 2025"
url = "http://furrycons.com/event/25421/furdance-budapest-2025"
startDate = "2025-09-26"
endDate = "2025-09-28"
address = "Csokonai Kulturális Központ, Budapest, Hungary"
country = "HU"
latLng = [ 47.5564366, 19.1133933,]
source = "fancons.com"
