name = "Furdance Budapest 2025"
url = "http://furrycons.com/event/25421/furdance-budapest-2025"
start_date = "2025-09-26"
end_date = "2025-09-28"
address = "Csokonai Kulturális Központ, Budapest, Hungary"
country = "HU"
lat_lng = [47.5564366, 19.1133933]
