name = "FurEast 2025"
url = "http://furrycons.com/event/25482/fureast-2025"
start_date = "2025-08-01"
end_date = "2025-08-03"
address = "Hilton Strasbourg, Strasbourg, France"
country = "FR"
lat_lng = [48.5969119, 7.7550027]
