name = "Furever West 2025"
url = "http://furrycons.com/event/26018/furever-west-2025"
start_date = "2025-09-19"
end_date = "2025-09-21"
address = "Hilton Garden Inn Laramie, Laramie, WY, USA"
country = "US"
lat_lng = [41.3101524, -105.5638466]
