name = "Furpocalypse 2025"
url = "http://furrycons.com/event/25964/furpocalypse-2025"
startDate = "2025-10-30"
endDate = "2025-11-02"
address = "Hilton Stamford Hotel & Executive Meeting Center, Stamford, CT, USA"
country = "US"
latLng = [ 41.0432058, -73.5503999,]
