name = "Furror 2025"
url = "http://furrycons.com/event/26209/furror-2025"
startDate = "2025-10-10"
endDate = "2025-10-12"
address = "Boutique Hotel's III Piłsudskiego, Łódź, Poland"
country = "PL"
latLng = [51.7601428, 19.460568]
