name = "Furry Blacklight 2025"
url = "http://furrycons.com/event/25193/furry-blacklight-2025"
start_date = "2025-10-29"
end_date = "2025-11-02"
address = "H4 Hotel Wyndham Paris Pleyel Resort, Saint-Denis, France"
country = "FR"
lat_lng = [48.9201886, 2.3452041]
