name = "Furrest City 2025"
url = "http://furrycons.com/event/26112/furrest-city-2025"
start_date = "2025-09-13"
end_date = "2025-09-13"
address = "Sears think[box], Cleveland, OH, USA"
country = "US"
lat_lng = [41.5005593, -81.6056834]
