name = "Furry Cruise 2025"
url = "http://furrycons.com/event/26021/furry-cruise-2025"
start_date = "2025-10-03"
end_date = "2025-10-10"
address = "Norwegian Gem, Departing from Boston, MA, USA"
country = "US"
lat_lng = [42.3437594, -71.0307895]
