name = "Furry Retreat 2025"
url = "http://furrycons.com/event/26019/furry-retreat-2025"
startDate = "2025-10-01"
endDate = "2025-10-06"
address = "Robbers Cave State Park, Wilburton, OK, USA"
country = "US"
latLng = [ 34.9803592, -95.3500819,]
