name = "Furrydelphia 2025"
url = "http://furrycons.com/event/24844/furrydelphia-2025"
start_date = "2025-08-22"
end_date = "2025-08-24"
address = "Sheraton Downtown Philadelphia, Philadelphia, PA, USA"
country = "US"
lat_lng = [39.9572347, -75.1670743]
