name = "Furry Retreat 2025"
url = "http://furrycons.com/event/26019/furry-retreat-2025"
start_date = "2025-10-01"
end_date = "2025-10-06"
address = "Robbers Cave State Park, Wilburton, OK, USA"
country = "US"
lat_lng = [34.9803592, -95.3500819]
