name = "Furry Cruise 2025"
url = "http://furrycons.com/event/26021/furry-cruise-2025"
startDate = "2025-10-03"
endDate = "2025-10-10"
address = "Norwegian Gem, Departing from Boston, MA, USA"
country = "US"
latLng = [ 42.3437594, -71.0307895,]
