name = "Furry Migration 2025"
url = "http://furrycons.com/event/24633/furry-migration-2025"
startDate = "2025-09-05"
endDate = "2025-09-07"
address = "Hyatt Regency Minneapolis, Minneapolis, MN, USA"
country = "US"
latLng = [44.9706891, -93.2784744]
