name = "Furry R Con 2025"
url = "http://furrycons.com/event/25843/furry-r-con-2025"
start_date = "2025-09-11"
end_date = "2025-09-14"
address = "Chaty pod Gýmešom, Jelenec, Slovakia"
country = "SK"
lat_lng = [48.399078, 18.2092043]
