name = "Furry Migration 2025"
url = "http://furrycons.com/event/24633/furry-migration-2025"
start_date = "2025-09-05"
end_date = "2025-09-07"
address = "Hyatt Regency Minneapolis, Minneapolis, MN, USA"
country = "US"
lat_lng = [44.9706891, -93.2784744]
