name = "FursonaCon 2025"
url = "http://furrycons.com/event/25369/fursonacon-2025"
start_date = "2025-08-28"
end_date = "2025-08-31"
address = "Newport News Marriott at City Center, Newport News, VA, USA"
country = "US"
lat_lng = [37.0869102, -76.4712476]
