name = "Furs Upon Malaysia 2025"
url = "http://furrycons.com/event/26210/furs-upon-malaysia-2025"
startDate = "2025-12-13"
endDate = "2025-12-14"
address = "Hotel Armada Petaling Jaya, Petaling Jaya, Selangor, Malaysia"
country = "MY"
latLng = [ 3.1042927, 101.6408144,]
source = "fancons.com"
