name = "Further Confusion 2026"
url = "http://furrycons.com/event/26069/further-confusion-2026"
startDate = "2026-01-15"
endDate = "2026-01-19"
address = "San Jose McEnery Convention Center, San Jose, CA, USA"
country = "US"
latLng = [ 37.329061, -121.8888761,]
