name = "Furvana 2025"
url = "http://furrycons.com/event/25983/furvana-2025"
start_date = "2025-09-05"
end_date = "2025-09-07"
address = "Ocean Shores Convention Center, Ocean Shores, WA, USA"
country = "US"
lat_lng = [47.0084857, -124.1635001]
