name = "Furvana 2025"
url = "http://furrycons.com/event/25983/furvana-2025"
startDate = "2025-09-05"
endDate = "2025-09-07"
address = "Ocean Shores Convention Center, Ocean Shores, WA, USA"
country = "US"
latLng = [ 47.0084857, -124.1635001,]
