name = "Futerkon 2025"
url = "http://furrycons.com/event/25299/futerkon-2025"
startDate = "2025-08-06"
endDate = "2025-08-10"
address = "Hotel Ameliówka, Mąchocice Kapitulne, Poland"
country = "PL"
latLng = [ 50.8977634, 20.7817025,]
