name = "Futerkon 2025"
url = "http://furrycons.com/event/25299/futerkon-2025"
start_date = "2025-08-06"
end_date = "2025-08-10"
address = "Hotel Ameliówka, Mąchocice Kapitulne, Poland"
country = "PL"
lat_lng = [50.8977634, 20.7817025]
