name = "Futrołajki 2025"
url = "http://furrycons.com/event/25887/futroajki-2025"
start_date = "2025-11-12"
end_date = "2025-11-16"
address = "Grand Hotel Kielce, Kielce, Poland"
country = "PL"
lat_lng = [50.8742279, 20.6202811]
