name = "Futrołajki 2025"
url = "http://furrycons.com/event/25887/futroajki-2025"
startDate = "2025-11-12"
endDate = "2025-11-16"
address = "Grand Hotel Kielce, Kielce, Poland"
country = "PL"
latLng = [ 50.8742279, 20.6202811,]
