name = "Gateway FurMeet 2025"
url = "http://furrycons.com/event/25614/gateway-furmeet-2025"
start_date = "2025-10-03"
end_date = "2025-10-05"
address = "Hilton St. Louis at the Ballpark, St. Louis, MO, USA"
country = "US"
lat_lng = [38.6252565, -90.1912512]
