name = "Genderverse FurCon 2025"
url = "http://furrycons.com/event/24561/genderverse-furcon-2025"
startDate = "2025-09-20"
endDate = "2025-09-20"
address = "Delta Hotels Toronto Airport & Conference Centre, Toronto, Ontario, Canada"
country = "CA"
latLng = [43.6890448, -79.5778256]
