name = "Get Out The Float 2026"
url = "http://furrycons.com/event/26024/get-out-the-float-2026"
start_date = "2026-02-12"
end_date = "2026-02-15"
address = "Seaside Civic & Convention Center, Seaside, OR, USA"
country = "US"
lat_lng = [45.9941334, -123.9253055]
