name = "Get Out The Float 2026"
url = "http://furrycons.com/event/26024/get-out-the-float-2026"
startDate = "2026-02-12"
endDate = "2026-02-15"
address = "Seaside Civic & Convention Center, Seaside, OR, USA"
country = "US"
latLng = [45.9941334, -123.9253055]
