name = "GoldenHorn 2025"
url = "http://furrycons.com/event/25058/goldenhorn-2025"
start_date = "2025-11-13"
end_date = "2025-11-16"
address = "Adria Ankaran Hotel & Resort, Ankaran, Slovenia"
country = "SI"
lat_lng = [45.5782072, 13.7338598]
