name = "H-Con 2025"
url = "http://furrycons.com/event/26061/h-con-2025"
startDate = "2025-10-01"
endDate = "2025-10-05"
address = "Petershof, Erbach, Germany"
country = "DE"
latLng = [49.6404757, 9.0459292]
