name = "Heartland Howloween 2025"
url = "http://furrycons.com/event/26063/heartland-howloween-2025"
startDate = "2025-10-10"
endDate = "2025-10-12"
address = "Comfort Inn & Suites Omaha Central, Omaha, NE, USA"
country = "US"
latLng = [41.226076, -96.022218]
