name = "Howloween 2025"
url = "http://furrycons.com/event/25994/howloween-2025"
start_date = "2025-10-23"
end_date = "2025-10-26"
address = "Executive Hotel Vancouver Airport, Richmond, British Columbia, Canada"
country = "CA"
lat_lng = [49.1706812, -123.1451646]
