name = "Howloween 2025"
url = "http://furrycons.com/event/25994/howloween-2025"
startDate = "2025-10-23"
endDate = "2025-10-26"
address = "Executive Hotel Vancouver Airport, Richmond, British Columbia, Canada"
country = "CA"
latLng = [ 49.1706812, -123.1451646,]
source = "fancons.com"
