name = "IndyFurCon 2025"
url = "http://furrycons.com/event/25911/indyfurcon-2025"
startDate = "2025-08-15"
endDate = "2025-08-17"
address = "Wyndham Indianapolis Airport, Indianapolis, IN, USA"
country = "US"
latLng = [39.7290633, -86.2586527]
