name = "Infurnity 2025"
url = "http://furrycons.com/event/25984/infurnity-2025"
start_date = "2025-10-31"
end_date = "2025-11-02"
address = "Fullon Hotel Lihpao Land, Taichung City, Taiwan"
country = "TW"
lat_lng = [24.3236953, 120.6963401]
