name = "Kemocon 2025"
url = "http://furrycons.com/event/26045/kemocon-2025"
start_date = "2025-11-07"
end_date = "2025-11-09"
address = "Toki no Sumika, Gotemba, Japan"
country = "JP"
lat_lng = [35.236037, 138.9253249]
