name = "Las Vegas Fur Con 2026"
url = "http://furrycons.com/event/26132/las-vegas-fur-con-2026"
startDate = "2026-04-02"
endDate = "2026-04-05"
address = "Alexis Park Resort, Las Vegas, NV, USA"
country = "US"
latLng = [ 36.1073746, -115.1566743,]
source = "fancons.com"
