name = "Megaplex 2025"
url = "http://furrycons.com/event/25484/megaplex-2025"
start_date = "2025-08-30"
end_date = "2025-09-01"
address = "Hyatt Regency Orlando, Orlando, FL, USA"
country = "US"
lat_lng = [28.4271946, -81.46749]
