name = "Mephit Fur Meet 2025"
url = "http://furrycons.com/event/25975/mephit-fur-meet-2025"
startDate = "2025-08-29"
endDate = "2025-08-31"
address = "Memphis Vitality Hotel, Memphis, TN, USA"
country = "US"
latLng = [ 35.0768111, -89.903563,]
