name = "Midwest FurFest 2025"
url = "http://furrycons.com/event/25878/midwest-furfest-2025"
startDate = "2025-12-04"
endDate = "2025-12-07"
address = "Donald E. Stephens Convention Center, Rosemont, IL, USA"
country = "US"
latLng = [ 41.9792212, -87.8611418,]
source = "fancons.com"
