name = "Midwest FurFest 2025"
url = "http://furrycons.com/event/25878/midwest-furfest-2025"
start_date = "2025-12-04"
end_date = "2025-12-07"
address = "Donald E. Stephens Convention Center, Rosemont, IL, USA"
country = "US"
lat_lng = [41.9792212, -87.8611418]
