name = "Nashum FurCon 2026"
url = "http://furrycons.com/event/25844/nashum-furcon-2026"
start_date = "2026-05-22"
end_date = "2026-05-24"
address = "Sheraton Music City Nashville Airport, Nashville, TN, USA"
country = "US"
lat_lng = [36.144359, -86.6830745]
