name = "NordicFuzzCon 2026"
url = "http://furrycons.com/event/25979/nordicfuzzcon-2026"
startDate = "2026-02-18"
endDate = "2026-02-22"
address = "Clarion Hotel & Congress Malmö Live, Malmö, Sweden"
country = "SE"
latLng = [ 55.6074523, 12.9941926,]
