name = "NordicFuzzCon 2026"
url = "http://furrycons.com/event/25979/nordicfuzzcon-2026"
start_date = "2026-02-18"
end_date = "2026-02-22"
address = "Clarion Hotel & Congress Malmö Live, Malmö, Sweden"
country = "SE"
lat_lng = [55.6074523, 12.9941926]
