name = "PAWCon 2025"
url = "http://furrycons.com/event/25717/pawcon-2025"
start_date = "2025-11-07"
end_date = "2025-11-09"
address = "DoubleTree by Hilton Hotel San Jose, San Jose, CA, USA"
country = "US"
lat_lng = [37.3718206, -121.9228001]
