name = "PAWCon 2025"
url = "http://furrycons.com/event/25717/pawcon-2025"
startDate = "2025-11-07"
endDate = "2025-11-09"
address = "DoubleTree by Hilton Hotel San Jose, San Jose, CA, USA"
country = "US"
latLng = [ 37.3718206, -121.9228001,]
