name = "Pawsome 2025"
url = "http://furrycons.com/event/25963/pawsome-2025"
startDate = "2025-10-03"
endDate = "2025-10-06"
address = "Mercure Gloucester Bowden Hall Hotel, Gloucester, UK"
country = "GB"
latLng = [ 51.8340083, -2.1883852,]
