name = "Pawska 2025"
url = "http://furrycons.com/event/25483/pawska-2025"
start_date = "2025-11-28"
end_date = "2025-11-30"
address = "Amber Hotel Gdańsk, Gdańsk, Poland"
country = "PL"
lat_lng = [54.3580297, 18.6215472]
