name = "PortConMaine 2026"
url = "http://furrycons.com/event/26329/portconmaine-2026"
start_date = "2026-06-25"
end_date = "2026-06-28"
address = "Holiday Inn Portland-By The Bay, Portland, ME, USA"
country = "US"
lat_lng = [43.6534888, -70.2608888]
