name = "Reffurence 2025"
url = "http://furrycons.com/event/25046/reffurence-2025"
start_date = "2025-10-30"
end_date = "2025-11-02"
address = "Hotel Zuiderduin, Egmond aan Zee, Netherlands"
country = "NL"
lat_lng = [52.6164703, 4.6247934]
