name = "Santiago Anthro Fest 2026"
url = "http://furrycons.com/event/26345/santiago-anthro-fest-2026"
start_date = "2026-02-26"
end_date = "2026-03-01"
address = "Almacruz Hotel y Centro de Convenciones, Santiago, Chile"
country = "CL"
lat_lng = [-33.442136, -70.6474291]
