name = "Santiago Anthro Fest 2026"
url = "http://furrycons.com/event/26345/santiago-anthro-fest-2026"
startDate = "2026-02-26"
endDate = "2026-03-01"
address = "Almacruz Hotel y Centro de Convenciones, Santiago, Chile"
country = "CL"
latLng = [ -33.442136, -70.6474291,]
source = "fancons.com"
