name = "Scotiacon 2026"
url = "http://furrycons.com/event/25476/scotiacon-2026"
start_date = "2026-02-06"
end_date = "2026-02-09"
address = "Crowne Plaza Glasgow, Glasgow, UK"
country = "GB"
lat_lng = [55.8597859, -4.2897379]
