name = "South Afrifur 2025"
url = "http://furrycons.com/event/26055/south-afrifur-2025"
startDate = "2025-09-05"
endDate = "2025-09-08"
address = "Valverde Eco Hotel, Muldersdrif Lanseria, South Africa"
country = "ZA"
latLng = [ -25.9556957, 27.8763192,]
