name = "Tails and Tornadoes Fur Con 2025"
url = "http://furrycons.com/event/25772/tails-and-tornadoes-fur-con-2025"
start_date = "2025-09-05"
end_date = "2025-09-07"
address = "Renaissance Tulsa Hotel & Convention Center, Tulsa, OK, USA"
country = "US"
lat_lng = [36.0650505, -95.8577575]
