name = "Texas Furry Siesta 2025"
url = "http://furrycons.com/event/25353/texas-furry-siesta-2025"
start_date = "2025-08-14"
end_date = "2025-08-17"
address = "Hyatt Regency Dallas, Dallas, TX, USA"
country = "US"
lat_lng = [32.7755992, -96.809601]
