name = "VancouFur 2026"
url = "http://furrycons.com/event/26299/vancoufur-2026"
start_date = "2026-03-05"
end_date = "2026-03-08"
address = "Richmond Conference Centre, Richmond, British Columbia, Canada"
country = "CA"
lat_lng = [49.1710571, -123.1414519]
