name = "VancouFur 2026"
url = "http://furrycons.com/event/26299/vancoufur-2026"
startDate = "2026-03-05"
endDate = "2026-03-08"
address = "Richmond Conference Centre, Richmond, British Columbia, Canada"
country = "CA"
latLng = [ 49.1710571, -123.1414519,]
