name = "West Aussie Fur Frenzy 2025"
url = "http://furrycons.com/event/26043/west-aussie-fur-frenzy-2025"
start_date = "2025-09-19"
end_date = "2025-09-21"
address = "Esplanade Hotel Fremantle by Rydges, Fremantle, Western Australia, Australia"
country = "AU"
lat_lng = [-32.056909, 115.7458664]
