name = "Western PA Furry Weekend 2025"
url = "http://furrycons.com/event/26020/western-pa-furry-weekend-2025"
start_date = "2025-10-03"
end_date = "2025-10-05"
address = "North Park Lodge, Allison Park, PA, USA"
country = "US"
lat_lng = [40.6170415, -80.0170688]
