name = "Wild Nights 2026"
url = "http://furrycons.com/event/25897/wild-nights-2026"
startDate = "2026-04-23"
endDate = "2026-04-28"
address = "Robbers Cave State Park, Wilburton, OK, USA"
country = "US"
latLng = [ 34.9803592, -95.3500819,]
