name = "Wild North 2025"
url = "http://furrycons.com/event/25992/wild-north-2025"
startDate = "2025-09-26"
endDate = "2025-09-29"
address = "Lumley Castle, Chester-le-Street, UK"
country = "GB"
latLng = [54.8533855, -1.5532119]
