name = "World Wild Fur Camp 2025"
url = "http://furrycons.com/event/26105/world-wild-fur-camp-2025"
startDate = "2025-10-17"
endDate = "2025-10-19"
address = "YMCA Camp Willson, Bellefontaine, OH, USA"
country = "US"
latLng = [ 40.3537857, -83.8093439,]
