name: Edit convention
description: Request an edit to convention information
title: "Edit convention: "
labels:
  - edit
body:
  - type: markdown
    attributes:
      value: |
        All information must be verifiable from official sources for the convention.

        For anything that doesn't need to be updated, you may leave the field blank.

  - id: name
    type: input
    attributes:
      label: Name
      description: The name of the convention.
      placeholder: e.g. My Cool Furry Con
    validations:
      required: true

  - id: url
    type: input
    attributes:
      label: Website
      description: The convention's website.
      placeholder: e.g. https://mycoolfurrycon.com

  - id: startDate
    type: input
    attributes:
      label: Start date
      description: The start date of the convention, as yyyy-MM-dd.
      placeholder: e.g. 2000-02-03

  - id: endDate
    type: input
    attributes:
      label: End date
      description: The end date of the convention, as yyyy-MM-dd.
      placeholder: e.g. 2000-02-09

  - id: venue
    type: input
    attributes:
      label: Venue
      description: The convention's venue.
      placeholder: e.g. Fuzz E. Wuzzy Convention Center

  - id: comments
    type: textarea
    attributes:
      label: Anything else?
      description: |
        Anything else you'd like to add about your request.
