name: deploy
on:
  push:
    branches:
      - main

  workflow_run:
    workflows:
      - fancons_import
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: |
          git config --global user.name "cons.fyi GitHub bot"
          git config --global user.email "github@cons.fyi"
      - run: mkdir $RUNNER_TEMP/out
      - run: ./.tools/digest.py
        env:
          OUTPUT_DIR: "${{ runner.temp }}/out"
      - run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "via digest"
          git push
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "${{ runner.temp }}/out"
      - uses: actions/deploy-pages@v4
      - run: curl --fail-with-body -u $TRIGGER_KEY -XPOST https://bsky-labeler.cons.fyi/trigger
        env:
          TRIGGER_KEY: ${{ secrets.TRIGGER_KEY }}
