name: deploy
on:
  push:
    branches:
      - main

  workflow_run:
    workflows:
      - import_furdu
      - import_fancons
      - import_concat
      - import_rams
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: |
          mkdir "$RUNNER_TEMP/out" &&
          ./tools/materialize.py "$RUNNER_TEMP/out" &&
          ./tools/render_markdown.py < README.md > "$RUNNER_TEMP/out/index.html" &&
          ./tools/render_index.py "$RUNNER_TEMP/out/series" data.cons.fyi/series > "$RUNNER_TEMP/out/series/index.html" &&
          ./tools/render_index.py "$RUNNER_TEMP/out/events" data.cons.fyi/events > "$RUNNER_TEMP/out/events/index.html"
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "${{ runner.temp }}/out"
      - uses: actions/deploy-pages@v4
      - run: curl --fail-with-body -u $BSKY_LABELER_TRIGGER_KEY -XPOST https://bsky-labeler.cons.fyi/trigger
        env:
          BSKY_LABELER_TRIGGER_KEY: ${{ secrets.BSKY_LABELER_TRIGGER_KEY }}
