name: deploy
on:
  push:
    branches:
      - main

  workflow_run:
    workflows:
      - fancons_import
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: mkdir $RUNNER_TEMP/out
      - run: ./.tools/digest.py
        env:
          OUTPUT_DIR: "${{ runner.temp }}/out"
      - run: ./.tools/render_markdown.py < README.md > "${{ runner.temp }}/out/index.html"
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "${{ runner.temp }}/out"
      - uses: actions/deploy-pages@v4
      - run: curl --fail-with-body -u $TRIGGER_KEY -XPOST https://bsky-labeler.cons.fyi/trigger
        env:
          TRIGGER_KEY: ${{ secrets.TRIGGER_KEY }}
